### ISSUE TITLE
大神求指导！能否提供简单易懂的操作教程

### ISSUE THREAD

**Issue by 8min20sec** [fyqc/cool18#4]
如题，完全是技术上的小白，对于您对于作品的创造我是完全是膜拜式敬佩的！
当因为对于技术的基础知识上的完全空白，甚至对于您的自述文件都看着很吃力，更遑论实际操作了。
可否烦请大神在闲暇之余略作指导，怎样根据您提供的代码文件进行文章的下载，这都需要哪些软件，又如何进行具体的设置和操作，能让像我这种完全的非业内人士也能上手使用！球球了！

**Comment by fyqc** [comment]
你需要学习一下Python的使用，找本书或者教程吧。
